FROM ubuntu:bionic

# Update and install necessary packages
RUN apt-get update && \
    apt-get install -y unzip curl libcurl4 libssl1.1

# Copy the manually downloaded Bedrock server zip file into the Docker container
COPY bedrock-server.zip /bedrock-server.zip

# Unzip the Bedrock server and set executable permissions
RUN unzip /bedrock-server.zip -d bedrock-server && \
    chmod +x bedrock-server/bedrock_server && \
    rm /bedrock-server.zip

# Set working directory
WORKDIR /bedrock-server

# Set the necessary environment variables
ENV LD_LIBRARY_PATH=.

# Default command to run the server
CMD ./bedrock_server
